id: P75A75253
initial_creation_type: input
source_metadata:
  title: Madhyamakāvatāra Series
  language: bo
  description: 'Texts related to the Madhyamakāvatāra (dbu ma la ’jug pa), or Introduction
    to the Middle Way, by Candrakīrti:'
  volume:
    ed626350960d454a8ef32bdde092e423:
      title: Commentary on the Madhyamakāvatāra—Part 1—Collection of Reasoning
      parent: Commentary
    58e43c5cfe2e42d586b18a2b91696c16:
      title: Commentary on the Madhyamakāvatāra—Part 2—Title and Translators Homage
      parent: Commentary
    5ec96ee4f03b40d28b348fb53022b242:
      title: Prologue to Introduction to the Middle Way (Madhyamakāvatāra)
      parent: Prologue
created_at: '2022-03-01T04:30:16.731447'
last_modified_at: '2022-03-01T04:30:16.731450'
